import Head from "next/head";
import Card from "src/components/card/card";


export default function Home() {
  return (
    <>
      <Head>
        <title>DecorHome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Card />
      </div>
    </>
  );
}
